public enum EventKey
{
    NONE = -1,
    AddBuff = 0,
    CastBuff = 1,
    FinishBuff = 2,
    UpdateCurrency = 3,
    AttackEventByWeapon = 4,
    GameClear=100,
    StageFinish=101,
    CritDamage,
    KilledBy,
    DamageToHealth,
    RerollBuff,
    CastBuffToMainPlayer,
    PickBuffDone,
    BeforeHit,
    EnhanceSuccess,
    UpRaritySuccess,
    UnEquipItem,
    EquipItem,
    PreFire,
    SelectBuff,
    GameLoaded,
    StopMovement,
    ContinueMovement,
    CharacterLanded,
    SortItemRarity,
    RarityMerge_PickItem,
    PickHero,
    PressKeyControl,
    ReleaseKeyControl,
    TriggerAttack,
    PreSpeedFireBullet,
    PortalTeleport,
    PlayerTeleported,
    TriggerPortal,
    EnableControl,
    DisableControl,
    StageStart,
    GetHit,
    BulletImpact,
    UpdateHeroItemUI,
    ActorSpawn,
    ReverseEquipment,
    UpdateFragment,
    RarityMerge_UnPickItem,
    RarityMerge_PickMainItem,
    RarityMerge_UnPickMainItem,
    RarityMerge_UpdateView,
    RarityMerge_Successful,
    UpdateBag,
    UpdateResource,
    ShowCooldownWave,

    TutMove =1000,
    TutRun,
    TutJump,
    TutHoldJump,
    TutShoot,
    TutJumpPlatform,
    TutDescend,
    TutDoubleJump,
    ShowHandTut,
    HideHandTut,
    EnterRoom,
    DroneSpawn,
    ClaimQuest,

    
    OnBulletMove=10000,
    BossChestSpawned,
    BossChestHidden,
    BossChestTrigger,
    ChangeLanguage,
    HeroUpgradeStarSuccess,
    HeroUpgradeLevelSuccess,
    JetPackTriggered,
    JetPackReleased,
    ActorSpawnPortal,
    FreezeTime,
    ChangePlayer,
    ClaimDungeonWorld,
    OnCastSkill,
    SelectMap,
    ChangeDrone,
    OnBoomerangShoot,
    GameStart,
    WaveStart,
    WaveCountDown,
    PurchaseX3Gift,
    CharacterDesend,
    EnemyAllySpawn,
    OnBulletImpact,
    ImmuneAttack,
    SelectHeroInventory,
    SpeedBoost,
    QuickEquip,
    OnAttack,
    BeforeHit2,
    ActorSpawnPortalWithCustomVFX,
    AutoDestroyActor,
    AttackEvent,
    BuyPremiumBattlePass,
    OnCharacterJump,
    SpawnEffect,
    OnHealthBarSpawn
}