using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class DB_Equipment : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Equipment(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Equipment(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5517546562277333375UL,16665680798075242630UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.Int32 Id => _Id[Index];
	public System.String StatName => _StatName[Index];
	public System.Single StatValue => _StatValue[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5419922698562274805UL, 6820540367795764644UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Id;
	public static BansheeGz.BGDatabase.BGFieldInt _Id => _ufle12jhs77_Id ?? (_ufle12jhs77_Id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5566407069750613177UL, 10335210162240578486UL), () => _ufle12jhs77_Id = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_StatName;
	public static BansheeGz.BGDatabase.BGFieldString _StatName => _ufle12jhs77_StatName ?? (_ufle12jhs77_StatName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5764001884685377119UL, 14760467108199830417UL), () => _ufle12jhs77_StatName = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_StatValue;
	public static BansheeGz.BGDatabase.BGFieldFloat _StatValue => _ufle12jhs77_StatValue ?? (_ufle12jhs77_StatValue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5095502301976073399UL, 2049990875013841048UL), () => _ufle12jhs77_StatValue = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_DungeonWave.Factory _factory2_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonRoom.Factory _factory3_PFS = new DB_DungeonRoom.Factory();
	private static readonly DB_Enemy.Factory _factory4_PFS = new DB_Enemy.Factory();
	private DB_Equipment() : base(MetaDefault)
	{
	}
	private DB_Equipment(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Equipment(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Equipment(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Equipment FindEntity(Predicate<DB_Equipment> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_Equipment) entity)) as DB_Equipment;
	}
	public static List<DB_Equipment> FindEntities(Predicate<DB_Equipment> filter, List<DB_Equipment> result=null, Comparison<DB_Equipment> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Equipment> action, Predicate<DB_Equipment> filter=null, Comparison<DB_Equipment> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Equipment) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Equipment) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Equipment)e1,(DB_Equipment)e2));
	}
	public static DB_Equipment GetEntity(BGId entityId) => (DB_Equipment) MetaDefault.GetEntity(entityId);
	public static DB_Equipment GetEntity(int index) => (DB_Equipment) MetaDefault[index];
	public static DB_Equipment GetEntity(string entityName) => (DB_Equipment) MetaDefault.GetEntity(entityName);
}

public partial class DB_Dungeon : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Dungeon(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Dungeon(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4818500370345381636UL,12112608833673709454UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.Int32 DungeonId => _DungeonId[Index];
	public System.String WaveId => _WaveId[Index];
	public System.Int32 LevelEnemy => _LevelEnemy[Index];
	public System.Int32 Length => _Length[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5514940696674268650UL, 13652136585090338707UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_DungeonId;
	public static BansheeGz.BGDatabase.BGFieldInt _DungeonId => _ufle12jhs77_DungeonId ?? (_ufle12jhs77_DungeonId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4896735550038176748UL, 6009861749873254044UL), () => _ufle12jhs77_DungeonId = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_WaveId;
	public static BansheeGz.BGDatabase.BGFieldString _WaveId => _ufle12jhs77_WaveId ?? (_ufle12jhs77_WaveId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4852096918358621168UL, 6027905963135471513UL), () => _ufle12jhs77_WaveId = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_LevelEnemy;
	public static BansheeGz.BGDatabase.BGFieldInt _LevelEnemy => _ufle12jhs77_LevelEnemy ?? (_ufle12jhs77_LevelEnemy = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5428650345630066318UL, 15781350494818850959UL), () => _ufle12jhs77_LevelEnemy = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Length;
	public static BansheeGz.BGDatabase.BGFieldInt _Length => _ufle12jhs77_Length ?? (_ufle12jhs77_Length = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5387921634078018349UL, 8217284423485567383UL), () => _ufle12jhs77_Length = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_DungeonWave.Factory _factory2_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonRoom.Factory _factory3_PFS = new DB_DungeonRoom.Factory();
	private static readonly DB_Enemy.Factory _factory4_PFS = new DB_Enemy.Factory();
	private DB_Dungeon() : base(MetaDefault)
	{
	}
	private DB_Dungeon(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Dungeon(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Dungeon(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Dungeon FindEntity(Predicate<DB_Dungeon> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_Dungeon) entity)) as DB_Dungeon;
	}
	public static List<DB_Dungeon> FindEntities(Predicate<DB_Dungeon> filter, List<DB_Dungeon> result=null, Comparison<DB_Dungeon> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Dungeon> action, Predicate<DB_Dungeon> filter=null, Comparison<DB_Dungeon> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Dungeon) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Dungeon) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Dungeon)e1,(DB_Dungeon)e2));
	}
	public static DB_Dungeon GetEntity(BGId entityId) => (DB_Dungeon) MetaDefault.GetEntity(entityId);
	public static DB_Dungeon GetEntity(int index) => (DB_Dungeon) MetaDefault[index];
	public static DB_Dungeon GetEntity(string entityName) => (DB_Dungeon) MetaDefault.GetEntity(entityName);
}

public partial class DB_DungeonWave : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_DungeonWave(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_DungeonWave(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4990157615765109547UL,3494535935200191639UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.Int32 DungeonId => _DungeonId[Index];
	public System.String WaveId => _WaveId[Index];
	public System.Single Time => _Time[Index];
	public System.String TagRoom => _TagRoom[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5366010017051414604UL, 10006346666115524503UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_DungeonId;
	public static BansheeGz.BGDatabase.BGFieldInt _DungeonId => _ufle12jhs77_DungeonId ?? (_ufle12jhs77_DungeonId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5354055654384408094UL, 12990400814150112156UL), () => _ufle12jhs77_DungeonId = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_WaveId;
	public static BansheeGz.BGDatabase.BGFieldString _WaveId => _ufle12jhs77_WaveId ?? (_ufle12jhs77_WaveId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4709495632793061993UL, 1220619858917511055UL), () => _ufle12jhs77_WaveId = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Time;
	public static BansheeGz.BGDatabase.BGFieldFloat _Time => _ufle12jhs77_Time ?? (_ufle12jhs77_Time = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5079044473218793066UL, 14901558846892786345UL), () => _ufle12jhs77_Time = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_TagRoom;
	public static BansheeGz.BGDatabase.BGFieldString _TagRoom => _ufle12jhs77_TagRoom ?? (_ufle12jhs77_TagRoom = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4640880375180723800UL, 531656927368391845UL), () => _ufle12jhs77_TagRoom = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_DungeonWave.Factory _factory2_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonRoom.Factory _factory3_PFS = new DB_DungeonRoom.Factory();
	private static readonly DB_Enemy.Factory _factory4_PFS = new DB_Enemy.Factory();
	private DB_DungeonWave() : base(MetaDefault)
	{
	}
	private DB_DungeonWave(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_DungeonWave(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_DungeonWave(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_DungeonWave FindEntity(Predicate<DB_DungeonWave> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_DungeonWave) entity)) as DB_DungeonWave;
	}
	public static List<DB_DungeonWave> FindEntities(Predicate<DB_DungeonWave> filter, List<DB_DungeonWave> result=null, Comparison<DB_DungeonWave> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_DungeonWave> action, Predicate<DB_DungeonWave> filter=null, Comparison<DB_DungeonWave> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_DungeonWave) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_DungeonWave) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_DungeonWave)e1,(DB_DungeonWave)e2));
	}
	public static DB_DungeonWave GetEntity(BGId entityId) => (DB_DungeonWave) MetaDefault.GetEntity(entityId);
	public static DB_DungeonWave GetEntity(int index) => (DB_DungeonWave) MetaDefault[index];
	public static DB_DungeonWave GetEntity(string entityName) => (DB_DungeonWave) MetaDefault.GetEntity(entityName);
}

public partial class DB_DungeonRoom : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_DungeonRoom(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_DungeonRoom(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4996311168261086844UL,17105608705026604728UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.Int32 RoomId => _RoomId[Index];
	public System.String TagRoom => _TagRoom[Index];
	public System.String EnemyId => _EnemyId[Index];
	public System.Int32 ZoneId => _ZoneId[Index];
	public System.Int32 Amount => _Amount[Index];
	public System.Single MinSpace => _MinSpace[Index];
	public System.Single SpawnRadius => _SpawnRadius[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4855901571804254035UL, 16046109631722724530UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_RoomId;
	public static BansheeGz.BGDatabase.BGFieldInt _RoomId => _ufle12jhs77_RoomId ?? (_ufle12jhs77_RoomId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4616012975855000532UL, 5021378018325574577UL), () => _ufle12jhs77_RoomId = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_TagRoom;
	public static BansheeGz.BGDatabase.BGFieldString _TagRoom => _ufle12jhs77_TagRoom ?? (_ufle12jhs77_TagRoom = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5659442128284235183UL, 10107689593404029350UL), () => _ufle12jhs77_TagRoom = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_EnemyId;
	public static BansheeGz.BGDatabase.BGFieldString _EnemyId => _ufle12jhs77_EnemyId ?? (_ufle12jhs77_EnemyId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5269352506948269703UL, 6820994088356669828UL), () => _ufle12jhs77_EnemyId = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_ZoneId;
	public static BansheeGz.BGDatabase.BGFieldInt _ZoneId => _ufle12jhs77_ZoneId ?? (_ufle12jhs77_ZoneId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5236163468794805404UL, 16316801910151946147UL), () => _ufle12jhs77_ZoneId = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Amount;
	public static BansheeGz.BGDatabase.BGFieldInt _Amount => _ufle12jhs77_Amount ?? (_ufle12jhs77_Amount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4862466717177014009UL, 2159012243600996766UL), () => _ufle12jhs77_Amount = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_MinSpace;
	public static BansheeGz.BGDatabase.BGFieldFloat _MinSpace => _ufle12jhs77_MinSpace ?? (_ufle12jhs77_MinSpace = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5389828099849375965UL, 5856760878893186713UL), () => _ufle12jhs77_MinSpace = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_SpawnRadius;
	public static BansheeGz.BGDatabase.BGFieldFloat _SpawnRadius => _ufle12jhs77_SpawnRadius ?? (_ufle12jhs77_SpawnRadius = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5123580497121795006UL, 11898482407927773327UL), () => _ufle12jhs77_SpawnRadius = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_DungeonWave.Factory _factory2_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonRoom.Factory _factory3_PFS = new DB_DungeonRoom.Factory();
	private static readonly DB_Enemy.Factory _factory4_PFS = new DB_Enemy.Factory();
	private DB_DungeonRoom() : base(MetaDefault)
	{
	}
	private DB_DungeonRoom(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_DungeonRoom(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_DungeonRoom(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_DungeonRoom FindEntity(Predicate<DB_DungeonRoom> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_DungeonRoom) entity)) as DB_DungeonRoom;
	}
	public static List<DB_DungeonRoom> FindEntities(Predicate<DB_DungeonRoom> filter, List<DB_DungeonRoom> result=null, Comparison<DB_DungeonRoom> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_DungeonRoom> action, Predicate<DB_DungeonRoom> filter=null, Comparison<DB_DungeonRoom> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_DungeonRoom) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_DungeonRoom) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_DungeonRoom)e1,(DB_DungeonRoom)e2));
	}
	public static DB_DungeonRoom GetEntity(BGId entityId) => (DB_DungeonRoom) MetaDefault.GetEntity(entityId);
	public static DB_DungeonRoom GetEntity(int index) => (DB_DungeonRoom) MetaDefault[index];
	public static DB_DungeonRoom GetEntity(string entityName) => (DB_DungeonRoom) MetaDefault.GetEntity(entityName);
}

public partial class DB_Enemy : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Enemy(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Enemy(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4881486225735226932UL,7772313332750720688UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.String Id => _Id[Index];
	public System.String Path => _Path[Index];
	public System.Single Hp => _Hp[Index];
	public System.Single Damage => _Damage[Index];
	public System.Single Speed => _Speed[Index];
	public System.Single AttackSpeed => _AttackSpeed[Index];
	public System.Single iHp => _iHp[Index];
	public System.Single iDamage => _iDamage[Index];
	public System.Single iSpeed => _iSpeed[Index];
	public System.Single iAttackSpeed => _iAttackSpeed[Index];
	public System.Collections.Generic.List<System.String> Tags => _Tags[Index];
	public System.Single AttackRange => _AttackRange[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5628759239601722407UL, 11191562407163079553UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Id;
	public static BansheeGz.BGDatabase.BGFieldString _Id => _ufle12jhs77_Id ?? (_ufle12jhs77_Id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4950251145784339990UL, 3739287601053370810UL), () => _ufle12jhs77_Id = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Path;
	public static BansheeGz.BGDatabase.BGFieldString _Path => _ufle12jhs77_Path ?? (_ufle12jhs77_Path = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5718814828173295119UL, 14504112455402141088UL), () => _ufle12jhs77_Path = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Hp;
	public static BansheeGz.BGDatabase.BGFieldFloat _Hp => _ufle12jhs77_Hp ?? (_ufle12jhs77_Hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5345557200727483664UL, 4084568972135379860UL), () => _ufle12jhs77_Hp = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Damage;
	public static BansheeGz.BGDatabase.BGFieldFloat _Damage => _ufle12jhs77_Damage ?? (_ufle12jhs77_Damage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5463547984772435321UL, 16764506508148677042UL), () => _ufle12jhs77_Damage = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Speed;
	public static BansheeGz.BGDatabase.BGFieldFloat _Speed => _ufle12jhs77_Speed ?? (_ufle12jhs77_Speed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5177272716303341427UL, 12268436345836187828UL), () => _ufle12jhs77_Speed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_AttackSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _AttackSpeed => _ufle12jhs77_AttackSpeed ?? (_ufle12jhs77_AttackSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5079194265169754738UL, 15739651275040353453UL), () => _ufle12jhs77_AttackSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_iHp;
	public static BansheeGz.BGDatabase.BGFieldFloat _iHp => _ufle12jhs77_iHp ?? (_ufle12jhs77_iHp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5728507633407605544UL, 5317521178103452839UL), () => _ufle12jhs77_iHp = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_iDamage;
	public static BansheeGz.BGDatabase.BGFieldFloat _iDamage => _ufle12jhs77_iDamage ?? (_ufle12jhs77_iDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4632917543034827306UL, 6486289876517566648UL), () => _ufle12jhs77_iDamage = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_iSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _iSpeed => _ufle12jhs77_iSpeed ?? (_ufle12jhs77_iSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5173801307719795115UL, 15272749403386630792UL), () => _ufle12jhs77_iSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_iAttackSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _iAttackSpeed => _ufle12jhs77_iAttackSpeed ?? (_ufle12jhs77_iAttackSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4686206555625677081UL, 18054272801716197016UL), () => _ufle12jhs77_iAttackSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldListString _ufle12jhs77_Tags;
	public static BansheeGz.BGDatabase.BGFieldListString _Tags => _ufle12jhs77_Tags ?? (_ufle12jhs77_Tags = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldListString>(MetaDefault, new BGId(5022514516694601424UL, 16281606801646570140UL), () => _ufle12jhs77_Tags = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_AttackRange;
	public static BansheeGz.BGDatabase.BGFieldFloat _AttackRange => _ufle12jhs77_AttackRange ?? (_ufle12jhs77_AttackRange = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5490436642101842478UL, 589637579496802477UL), () => _ufle12jhs77_AttackRange = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_DungeonWave.Factory _factory2_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonRoom.Factory _factory3_PFS = new DB_DungeonRoom.Factory();
	private static readonly DB_Enemy.Factory _factory4_PFS = new DB_Enemy.Factory();
	private DB_Enemy() : base(MetaDefault)
	{
	}
	private DB_Enemy(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Enemy(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Enemy(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Enemy FindEntity(Predicate<DB_Enemy> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_Enemy) entity)) as DB_Enemy;
	}
	public static List<DB_Enemy> FindEntities(Predicate<DB_Enemy> filter, List<DB_Enemy> result=null, Comparison<DB_Enemy> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Enemy> action, Predicate<DB_Enemy> filter=null, Comparison<DB_Enemy> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Enemy) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Enemy) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Enemy)e1,(DB_Enemy)e2));
	}
	public static DB_Enemy GetEntity(BGId entityId) => (DB_Enemy) MetaDefault.GetEntity(entityId);
	public static DB_Enemy GetEntity(int index) => (DB_Enemy) MetaDefault[index];
	public static DB_Enemy GetEntity(string entityName) => (DB_Enemy) MetaDefault.GetEntity(entityName);
}
#pragma warning restore 414
