using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class DB_Equipment : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Equipment(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Equipment(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5517546562277333375UL,16665680798075242630UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.String IdEquipment => _IdEquipment[Index];
	public System.String ItemType => _ItemType[Index];
	public System.String StatName => _StatName[Index];
	public System.Single Stat => _Stat[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5419922698562274805UL, 6820540367795764644UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_IdEquipment;
	public static BansheeGz.BGDatabase.BGFieldString _IdEquipment => _ufle12jhs77_IdEquipment ?? (_ufle12jhs77_IdEquipment = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5566407069750613177UL, 10335210162240578486UL), () => _ufle12jhs77_IdEquipment = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_ItemType;
	public static BansheeGz.BGDatabase.BGFieldString _ItemType => _ufle12jhs77_ItemType ?? (_ufle12jhs77_ItemType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5764001884685377119UL, 14760467108199830417UL), () => _ufle12jhs77_ItemType = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_StatName;
	public static BansheeGz.BGDatabase.BGFieldString _StatName => _ufle12jhs77_StatName ?? (_ufle12jhs77_StatName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5095502301976073399UL, 2049990875013841048UL), () => _ufle12jhs77_StatName = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Stat;
	public static BansheeGz.BGDatabase.BGFieldFloat _Stat => _ufle12jhs77_Stat ?? (_ufle12jhs77_Stat = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5490931226185412915UL, 13299080881365621139UL), () => _ufle12jhs77_Stat = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_Enemy.Factory _factory2_PFS = new DB_Enemy.Factory();
	private static readonly DB_DungeonWave.Factory _factory3_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonWaveEvent.Factory _factory4_PFS = new DB_DungeonWaveEvent.Factory();
	private static readonly DB_Weapon.Factory _factory5_PFS = new DB_Weapon.Factory();
	private static readonly DB_GearPerk.Factory _factory6_PFS = new DB_GearPerk.Factory();
	private static readonly DB_GameConfig.Factory _factory7_PFS = new DB_GameConfig.Factory();
	private DB_Equipment() : base(MetaDefault)
	{
	}
	private DB_Equipment(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Equipment(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Equipment(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Equipment FindEntity(Predicate<DB_Equipment> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_Equipment) entity)) as DB_Equipment;
	}
	public static List<DB_Equipment> FindEntities(Predicate<DB_Equipment> filter, List<DB_Equipment> result=null, Comparison<DB_Equipment> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Equipment> action, Predicate<DB_Equipment> filter=null, Comparison<DB_Equipment> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Equipment) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Equipment) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Equipment)e1,(DB_Equipment)e2));
	}
	public static DB_Equipment GetEntity(BGId entityId) => (DB_Equipment) MetaDefault.GetEntity(entityId);
	public static DB_Equipment GetEntity(int index) => (DB_Equipment) MetaDefault[index];
	public static DB_Equipment GetEntity(string entityName) => (DB_Equipment) MetaDefault.GetEntity(entityName);
}

public partial class DB_Dungeon : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Dungeon(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Dungeon(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4818500370345381636UL,12112608833673709454UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.Int32 DungeonId => _DungeonId[Index];
	public System.String WaveId => _WaveId[Index];
	public System.Int32 LevelEnemy => _LevelEnemy[Index];
	public System.Int32 Length => _Length[Index];
	public System.Single DelayStart => _DelayStart[Index];
	public System.Single Frequency => _Frequency[Index];
	public System.Single RandomAdd => _RandomAdd[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5514940696674268650UL, 13652136585090338707UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_DungeonId;
	public static BansheeGz.BGDatabase.BGFieldInt _DungeonId => _ufle12jhs77_DungeonId ?? (_ufle12jhs77_DungeonId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4896735550038176748UL, 6009861749873254044UL), () => _ufle12jhs77_DungeonId = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_WaveId;
	public static BansheeGz.BGDatabase.BGFieldString _WaveId => _ufle12jhs77_WaveId ?? (_ufle12jhs77_WaveId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4852096918358621168UL, 6027905963135471513UL), () => _ufle12jhs77_WaveId = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_LevelEnemy;
	public static BansheeGz.BGDatabase.BGFieldInt _LevelEnemy => _ufle12jhs77_LevelEnemy ?? (_ufle12jhs77_LevelEnemy = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5428650345630066318UL, 15781350494818850959UL), () => _ufle12jhs77_LevelEnemy = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Length;
	public static BansheeGz.BGDatabase.BGFieldInt _Length => _ufle12jhs77_Length ?? (_ufle12jhs77_Length = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5387921634078018349UL, 8217284423485567383UL), () => _ufle12jhs77_Length = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_DelayStart;
	public static BansheeGz.BGDatabase.BGFieldFloat _DelayStart => _ufle12jhs77_DelayStart ?? (_ufle12jhs77_DelayStart = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5106250717991129557UL, 15940863006044014240UL), () => _ufle12jhs77_DelayStart = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Frequency;
	public static BansheeGz.BGDatabase.BGFieldFloat _Frequency => _ufle12jhs77_Frequency ?? (_ufle12jhs77_Frequency = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4776896933090657880UL, 6477711059681813918UL), () => _ufle12jhs77_Frequency = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_RandomAdd;
	public static BansheeGz.BGDatabase.BGFieldFloat _RandomAdd => _ufle12jhs77_RandomAdd ?? (_ufle12jhs77_RandomAdd = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5187880409492567394UL, 10935125371476704142UL), () => _ufle12jhs77_RandomAdd = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_Enemy.Factory _factory2_PFS = new DB_Enemy.Factory();
	private static readonly DB_DungeonWave.Factory _factory3_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonWaveEvent.Factory _factory4_PFS = new DB_DungeonWaveEvent.Factory();
	private static readonly DB_Weapon.Factory _factory5_PFS = new DB_Weapon.Factory();
	private static readonly DB_GearPerk.Factory _factory6_PFS = new DB_GearPerk.Factory();
	private static readonly DB_GameConfig.Factory _factory7_PFS = new DB_GameConfig.Factory();
	private DB_Dungeon() : base(MetaDefault)
	{
	}
	private DB_Dungeon(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Dungeon(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Dungeon(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Dungeon FindEntity(Predicate<DB_Dungeon> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_Dungeon) entity)) as DB_Dungeon;
	}
	public static List<DB_Dungeon> FindEntities(Predicate<DB_Dungeon> filter, List<DB_Dungeon> result=null, Comparison<DB_Dungeon> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Dungeon> action, Predicate<DB_Dungeon> filter=null, Comparison<DB_Dungeon> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Dungeon) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Dungeon) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Dungeon)e1,(DB_Dungeon)e2));
	}
	public static DB_Dungeon GetEntity(BGId entityId) => (DB_Dungeon) MetaDefault.GetEntity(entityId);
	public static DB_Dungeon GetEntity(int index) => (DB_Dungeon) MetaDefault[index];
	public static DB_Dungeon GetEntity(string entityName) => (DB_Dungeon) MetaDefault.GetEntity(entityName);
}

public partial class DB_Enemy : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Enemy(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Enemy(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4881486225735226932UL,7772313332750720688UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.String Id => _Id[Index];
	public System.String Path => _Path[Index];
	public System.Single Hp => _Hp[Index];
	public System.Single Damage => _Damage[Index];
	public System.Single Speed => _Speed[Index];
	public System.Single AttackSpeed => _AttackSpeed[Index];
	public System.Single iHp => _iHp[Index];
	public System.Single iDamage => _iDamage[Index];
	public System.Single iSpeed => _iSpeed[Index];
	public System.Single iAttackSpeed => _iAttackSpeed[Index];
	public System.Collections.Generic.List<System.String> Tags => _Tags[Index];
	public System.Single AttackRange => _AttackRange[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5628759239601722407UL, 11191562407163079553UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Id;
	public static BansheeGz.BGDatabase.BGFieldString _Id => _ufle12jhs77_Id ?? (_ufle12jhs77_Id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4950251145784339990UL, 3739287601053370810UL), () => _ufle12jhs77_Id = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Path;
	public static BansheeGz.BGDatabase.BGFieldString _Path => _ufle12jhs77_Path ?? (_ufle12jhs77_Path = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5718814828173295119UL, 14504112455402141088UL), () => _ufle12jhs77_Path = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Hp;
	public static BansheeGz.BGDatabase.BGFieldFloat _Hp => _ufle12jhs77_Hp ?? (_ufle12jhs77_Hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5345557200727483664UL, 4084568972135379860UL), () => _ufle12jhs77_Hp = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Damage;
	public static BansheeGz.BGDatabase.BGFieldFloat _Damage => _ufle12jhs77_Damage ?? (_ufle12jhs77_Damage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5463547984772435321UL, 16764506508148677042UL), () => _ufle12jhs77_Damage = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Speed;
	public static BansheeGz.BGDatabase.BGFieldFloat _Speed => _ufle12jhs77_Speed ?? (_ufle12jhs77_Speed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5177272716303341427UL, 12268436345836187828UL), () => _ufle12jhs77_Speed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_AttackSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _AttackSpeed => _ufle12jhs77_AttackSpeed ?? (_ufle12jhs77_AttackSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5079194265169754738UL, 15739651275040353453UL), () => _ufle12jhs77_AttackSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_iHp;
	public static BansheeGz.BGDatabase.BGFieldFloat _iHp => _ufle12jhs77_iHp ?? (_ufle12jhs77_iHp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5728507633407605544UL, 5317521178103452839UL), () => _ufle12jhs77_iHp = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_iDamage;
	public static BansheeGz.BGDatabase.BGFieldFloat _iDamage => _ufle12jhs77_iDamage ?? (_ufle12jhs77_iDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4632917543034827306UL, 6486289876517566648UL), () => _ufle12jhs77_iDamage = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_iSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _iSpeed => _ufle12jhs77_iSpeed ?? (_ufle12jhs77_iSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5173801307719795115UL, 15272749403386630792UL), () => _ufle12jhs77_iSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_iAttackSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _iAttackSpeed => _ufle12jhs77_iAttackSpeed ?? (_ufle12jhs77_iAttackSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4686206555625677081UL, 18054272801716197016UL), () => _ufle12jhs77_iAttackSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldListString _ufle12jhs77_Tags;
	public static BansheeGz.BGDatabase.BGFieldListString _Tags => _ufle12jhs77_Tags ?? (_ufle12jhs77_Tags = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldListString>(MetaDefault, new BGId(5022514516694601424UL, 16281606801646570140UL), () => _ufle12jhs77_Tags = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_AttackRange;
	public static BansheeGz.BGDatabase.BGFieldFloat _AttackRange => _ufle12jhs77_AttackRange ?? (_ufle12jhs77_AttackRange = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5490436642101842478UL, 589637579496802477UL), () => _ufle12jhs77_AttackRange = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_Enemy.Factory _factory2_PFS = new DB_Enemy.Factory();
	private static readonly DB_DungeonWave.Factory _factory3_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonWaveEvent.Factory _factory4_PFS = new DB_DungeonWaveEvent.Factory();
	private static readonly DB_Weapon.Factory _factory5_PFS = new DB_Weapon.Factory();
	private static readonly DB_GearPerk.Factory _factory6_PFS = new DB_GearPerk.Factory();
	private static readonly DB_GameConfig.Factory _factory7_PFS = new DB_GameConfig.Factory();
	private DB_Enemy() : base(MetaDefault)
	{
	}
	private DB_Enemy(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Enemy(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Enemy(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Enemy FindEntity(Predicate<DB_Enemy> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_Enemy) entity)) as DB_Enemy;
	}
	public static List<DB_Enemy> FindEntities(Predicate<DB_Enemy> filter, List<DB_Enemy> result=null, Comparison<DB_Enemy> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Enemy> action, Predicate<DB_Enemy> filter=null, Comparison<DB_Enemy> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Enemy) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Enemy) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Enemy)e1,(DB_Enemy)e2));
	}
	public static DB_Enemy GetEntity(BGId entityId) => (DB_Enemy) MetaDefault.GetEntity(entityId);
	public static DB_Enemy GetEntity(int index) => (DB_Enemy) MetaDefault[index];
	public static DB_Enemy GetEntity(string entityName) => (DB_Enemy) MetaDefault.GetEntity(entityName);
}

public partial class DB_DungeonWave : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_DungeonWave(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_DungeonWave(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5144449783210509049UL,7479618431436517778UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.String WaveId => _WaveId[Index];
	public System.Int32 MaxInMap => _MaxInMap[Index];
	public System.String DefaultEnemy => _DefaultEnemy[Index];
	public System.Int32 DefaultAmount => _DefaultAmount[Index];
	public System.Single DefaultCluster => _DefaultCluster[Index];
	public System.Single CameraSize => _CameraSize[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5199273315712751020UL, 7180544439930714030UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_WaveId;
	public static BansheeGz.BGDatabase.BGFieldString _WaveId => _ufle12jhs77_WaveId ?? (_ufle12jhs77_WaveId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5093171278526634684UL, 7265670424734474927UL), () => _ufle12jhs77_WaveId = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_MaxInMap;
	public static BansheeGz.BGDatabase.BGFieldInt _MaxInMap => _ufle12jhs77_MaxInMap ?? (_ufle12jhs77_MaxInMap = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4687777164443925627UL, 7988887299335917972UL), () => _ufle12jhs77_MaxInMap = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_DefaultEnemy;
	public static BansheeGz.BGDatabase.BGFieldString _DefaultEnemy => _ufle12jhs77_DefaultEnemy ?? (_ufle12jhs77_DefaultEnemy = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4872449555294330000UL, 11136832714392385672UL), () => _ufle12jhs77_DefaultEnemy = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_DefaultAmount;
	public static BansheeGz.BGDatabase.BGFieldInt _DefaultAmount => _ufle12jhs77_DefaultAmount ?? (_ufle12jhs77_DefaultAmount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4672096289431929998UL, 17955527991210361241UL), () => _ufle12jhs77_DefaultAmount = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_DefaultCluster;
	public static BansheeGz.BGDatabase.BGFieldFloat _DefaultCluster => _ufle12jhs77_DefaultCluster ?? (_ufle12jhs77_DefaultCluster = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5097424058560736049UL, 12085130021855477921UL), () => _ufle12jhs77_DefaultCluster = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_CameraSize;
	public static BansheeGz.BGDatabase.BGFieldFloat _CameraSize => _ufle12jhs77_CameraSize ?? (_ufle12jhs77_CameraSize = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4848391233012276917UL, 689522806608232622UL), () => _ufle12jhs77_CameraSize = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_Enemy.Factory _factory2_PFS = new DB_Enemy.Factory();
	private static readonly DB_DungeonWave.Factory _factory3_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonWaveEvent.Factory _factory4_PFS = new DB_DungeonWaveEvent.Factory();
	private static readonly DB_Weapon.Factory _factory5_PFS = new DB_Weapon.Factory();
	private static readonly DB_GearPerk.Factory _factory6_PFS = new DB_GearPerk.Factory();
	private static readonly DB_GameConfig.Factory _factory7_PFS = new DB_GameConfig.Factory();
	private DB_DungeonWave() : base(MetaDefault)
	{
	}
	private DB_DungeonWave(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_DungeonWave(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_DungeonWave(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_DungeonWave FindEntity(Predicate<DB_DungeonWave> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_DungeonWave) entity)) as DB_DungeonWave;
	}
	public static List<DB_DungeonWave> FindEntities(Predicate<DB_DungeonWave> filter, List<DB_DungeonWave> result=null, Comparison<DB_DungeonWave> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_DungeonWave> action, Predicate<DB_DungeonWave> filter=null, Comparison<DB_DungeonWave> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_DungeonWave) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_DungeonWave) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_DungeonWave)e1,(DB_DungeonWave)e2));
	}
	public static DB_DungeonWave GetEntity(BGId entityId) => (DB_DungeonWave) MetaDefault.GetEntity(entityId);
	public static DB_DungeonWave GetEntity(int index) => (DB_DungeonWave) MetaDefault[index];
	public static DB_DungeonWave GetEntity(string entityName) => (DB_DungeonWave) MetaDefault.GetEntity(entityName);
}

public partial class DB_DungeonWaveEvent : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_DungeonWaveEvent(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_DungeonWaveEvent(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4871765252713828611UL,2314720731915947906UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.String EventId => _EventId[Index];
	public System.String WaveId => _WaveId[Index];
	public System.String Enemy => _Enemy[Index];
	public System.Single Frequency => _Frequency[Index];
	public System.Int32 Max => _Max[Index];
	public System.Single Cluster => _Cluster[Index];
	public System.Single Chance => _Chance[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5086535514433118060UL, 1582930548383956865UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_EventId;
	public static BansheeGz.BGDatabase.BGFieldString _EventId => _ufle12jhs77_EventId ?? (_ufle12jhs77_EventId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4789340466822656901UL, 6183767132401948333UL), () => _ufle12jhs77_EventId = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_WaveId;
	public static BansheeGz.BGDatabase.BGFieldString _WaveId => _ufle12jhs77_WaveId ?? (_ufle12jhs77_WaveId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5311516809613237021UL, 8553127409402984107UL), () => _ufle12jhs77_WaveId = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Enemy;
	public static BansheeGz.BGDatabase.BGFieldString _Enemy => _ufle12jhs77_Enemy ?? (_ufle12jhs77_Enemy = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5111734664589835512UL, 16387060256869261988UL), () => _ufle12jhs77_Enemy = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Frequency;
	public static BansheeGz.BGDatabase.BGFieldFloat _Frequency => _ufle12jhs77_Frequency ?? (_ufle12jhs77_Frequency = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5170584109326192786UL, 4465977195211569290UL), () => _ufle12jhs77_Frequency = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Max;
	public static BansheeGz.BGDatabase.BGFieldInt _Max => _ufle12jhs77_Max ?? (_ufle12jhs77_Max = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5075216157934649214UL, 17383140627019052947UL), () => _ufle12jhs77_Max = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Cluster;
	public static BansheeGz.BGDatabase.BGFieldFloat _Cluster => _ufle12jhs77_Cluster ?? (_ufle12jhs77_Cluster = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5331692585234256210UL, 13803938486354973362UL), () => _ufle12jhs77_Cluster = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Chance;
	public static BansheeGz.BGDatabase.BGFieldFloat _Chance => _ufle12jhs77_Chance ?? (_ufle12jhs77_Chance = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4622173018493056856UL, 7812075392562688700UL), () => _ufle12jhs77_Chance = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_Enemy.Factory _factory2_PFS = new DB_Enemy.Factory();
	private static readonly DB_DungeonWave.Factory _factory3_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonWaveEvent.Factory _factory4_PFS = new DB_DungeonWaveEvent.Factory();
	private static readonly DB_Weapon.Factory _factory5_PFS = new DB_Weapon.Factory();
	private static readonly DB_GearPerk.Factory _factory6_PFS = new DB_GearPerk.Factory();
	private static readonly DB_GameConfig.Factory _factory7_PFS = new DB_GameConfig.Factory();
	private DB_DungeonWaveEvent() : base(MetaDefault)
	{
	}
	private DB_DungeonWaveEvent(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_DungeonWaveEvent(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_DungeonWaveEvent(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_DungeonWaveEvent FindEntity(Predicate<DB_DungeonWaveEvent> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_DungeonWaveEvent) entity)) as DB_DungeonWaveEvent;
	}
	public static List<DB_DungeonWaveEvent> FindEntities(Predicate<DB_DungeonWaveEvent> filter, List<DB_DungeonWaveEvent> result=null, Comparison<DB_DungeonWaveEvent> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_DungeonWaveEvent> action, Predicate<DB_DungeonWaveEvent> filter=null, Comparison<DB_DungeonWaveEvent> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_DungeonWaveEvent) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_DungeonWaveEvent) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_DungeonWaveEvent)e1,(DB_DungeonWaveEvent)e2));
	}
	public static DB_DungeonWaveEvent GetEntity(BGId entityId) => (DB_DungeonWaveEvent) MetaDefault.GetEntity(entityId);
	public static DB_DungeonWaveEvent GetEntity(int index) => (DB_DungeonWaveEvent) MetaDefault[index];
	public static DB_DungeonWaveEvent GetEntity(string entityName) => (DB_DungeonWaveEvent) MetaDefault.GetEntity(entityName);
}

public partial class DB_Weapon : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Weapon(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Weapon(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5733266747800506826UL,2906313785089472430UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.String IdEquipment => _IdEquipment[Index];
	public System.String DamageType => _DamageType[Index];
	public System.String Rarity => _Rarity[Index];
	public System.Single Damage => _Damage[Index];
	public System.Single CritChance => _CritChance[Index];
	public System.Single AttackSpeed => _AttackSpeed[Index];
	public System.Single RangeAttack => _RangeAttack[Index];
	public System.Single Knockback => _Knockback[Index];
	public System.Int32 Projectiles => _Projectiles[Index];
	public System.Single Velocity => _Velocity[Index];
	public System.Int32 Unlock => _Unlock[Index];
	public System.Int32 Price => _Price[Index];
	public System.Collections.Generic.List<System.String> OtherStat => _OtherStat[Index];
	public System.Collections.Generic.List<System.String> StatUI => _StatUI[Index];
	public System.String PrefabPath => _PrefabPath[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5486753898478038351UL, 5239391134350077865UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_IdEquipment;
	public static BansheeGz.BGDatabase.BGFieldString _IdEquipment => _ufle12jhs77_IdEquipment ?? (_ufle12jhs77_IdEquipment = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4981804874786085979UL, 16244036463475313287UL), () => _ufle12jhs77_IdEquipment = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_DamageType;
	public static BansheeGz.BGDatabase.BGFieldString _DamageType => _ufle12jhs77_DamageType ?? (_ufle12jhs77_DamageType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5699642348270128428UL, 13707322175264063133UL), () => _ufle12jhs77_DamageType = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Rarity;
	public static BansheeGz.BGDatabase.BGFieldString _Rarity => _ufle12jhs77_Rarity ?? (_ufle12jhs77_Rarity = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4988088137366009747UL, 16160078976621036681UL), () => _ufle12jhs77_Rarity = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Damage;
	public static BansheeGz.BGDatabase.BGFieldFloat _Damage => _ufle12jhs77_Damage ?? (_ufle12jhs77_Damage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5758352941000704615UL, 279227216087061904UL), () => _ufle12jhs77_Damage = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_CritChance;
	public static BansheeGz.BGDatabase.BGFieldFloat _CritChance => _ufle12jhs77_CritChance ?? (_ufle12jhs77_CritChance = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5061452086836100050UL, 8878766143557968550UL), () => _ufle12jhs77_CritChance = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_AttackSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _AttackSpeed => _ufle12jhs77_AttackSpeed ?? (_ufle12jhs77_AttackSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5061103369081572510UL, 14289651339761375674UL), () => _ufle12jhs77_AttackSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_RangeAttack;
	public static BansheeGz.BGDatabase.BGFieldFloat _RangeAttack => _ufle12jhs77_RangeAttack ?? (_ufle12jhs77_RangeAttack = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5222114336546005852UL, 4623160166658201224UL), () => _ufle12jhs77_RangeAttack = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Knockback;
	public static BansheeGz.BGDatabase.BGFieldFloat _Knockback => _ufle12jhs77_Knockback ?? (_ufle12jhs77_Knockback = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4755072541924824870UL, 13716102043652252847UL), () => _ufle12jhs77_Knockback = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Projectiles;
	public static BansheeGz.BGDatabase.BGFieldInt _Projectiles => _ufle12jhs77_Projectiles ?? (_ufle12jhs77_Projectiles = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5528723035083717624UL, 4646919761773980290UL), () => _ufle12jhs77_Projectiles = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Velocity;
	public static BansheeGz.BGDatabase.BGFieldFloat _Velocity => _ufle12jhs77_Velocity ?? (_ufle12jhs77_Velocity = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5036629961515111593UL, 16671435671602131903UL), () => _ufle12jhs77_Velocity = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Unlock;
	public static BansheeGz.BGDatabase.BGFieldInt _Unlock => _ufle12jhs77_Unlock ?? (_ufle12jhs77_Unlock = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5476332286798211034UL, 3161870350320855936UL), () => _ufle12jhs77_Unlock = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Price;
	public static BansheeGz.BGDatabase.BGFieldInt _Price => _ufle12jhs77_Price ?? (_ufle12jhs77_Price = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5116195100211045869UL, 3547864814218350503UL), () => _ufle12jhs77_Price = null));
	private static BansheeGz.BGDatabase.BGFieldListString _ufle12jhs77_OtherStat;
	public static BansheeGz.BGDatabase.BGFieldListString _OtherStat => _ufle12jhs77_OtherStat ?? (_ufle12jhs77_OtherStat = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldListString>(MetaDefault, new BGId(5133351617449095319UL, 9423277731382012345UL), () => _ufle12jhs77_OtherStat = null));
	private static BansheeGz.BGDatabase.BGFieldListString _ufle12jhs77_StatUI;
	public static BansheeGz.BGDatabase.BGFieldListString _StatUI => _ufle12jhs77_StatUI ?? (_ufle12jhs77_StatUI = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldListString>(MetaDefault, new BGId(4989954162410628540UL, 9319384909449173937UL), () => _ufle12jhs77_StatUI = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_PrefabPath;
	public static BansheeGz.BGDatabase.BGFieldString _PrefabPath => _ufle12jhs77_PrefabPath ?? (_ufle12jhs77_PrefabPath = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4720937353355097434UL, 6252373223130517137UL), () => _ufle12jhs77_PrefabPath = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_Enemy.Factory _factory2_PFS = new DB_Enemy.Factory();
	private static readonly DB_DungeonWave.Factory _factory3_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonWaveEvent.Factory _factory4_PFS = new DB_DungeonWaveEvent.Factory();
	private static readonly DB_Weapon.Factory _factory5_PFS = new DB_Weapon.Factory();
	private static readonly DB_GearPerk.Factory _factory6_PFS = new DB_GearPerk.Factory();
	private static readonly DB_GameConfig.Factory _factory7_PFS = new DB_GameConfig.Factory();
	private DB_Weapon() : base(MetaDefault)
	{
	}
	private DB_Weapon(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Weapon(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Weapon(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Weapon FindEntity(Predicate<DB_Weapon> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_Weapon) entity)) as DB_Weapon;
	}
	public static List<DB_Weapon> FindEntities(Predicate<DB_Weapon> filter, List<DB_Weapon> result=null, Comparison<DB_Weapon> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Weapon> action, Predicate<DB_Weapon> filter=null, Comparison<DB_Weapon> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Weapon) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Weapon) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Weapon)e1,(DB_Weapon)e2));
	}
	public static DB_Weapon GetEntity(BGId entityId) => (DB_Weapon) MetaDefault.GetEntity(entityId);
	public static DB_Weapon GetEntity(int index) => (DB_Weapon) MetaDefault[index];
	public static DB_Weapon GetEntity(string entityName) => (DB_Weapon) MetaDefault.GetEntity(entityName);
}

public partial class DB_GearPerk : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_GearPerk(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_GearPerk(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5311475314760370833UL,1448962693894215101UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.String IdEquipment => _IdEquipment[Index];
	public System.String IdGear => _IdGear[Index];
	public System.String Rarity => _Rarity[Index];
	public System.String PerkType => _PerkType[Index];
	public System.String PerkStat => _PerkStat[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5223371704835465689UL, 12933659539986564777UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_IdEquipment;
	public static BansheeGz.BGDatabase.BGFieldString _IdEquipment => _ufle12jhs77_IdEquipment ?? (_ufle12jhs77_IdEquipment = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5399570341228644548UL, 7523359246678619820UL), () => _ufle12jhs77_IdEquipment = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_IdGear;
	public static BansheeGz.BGDatabase.BGFieldString _IdGear => _ufle12jhs77_IdGear ?? (_ufle12jhs77_IdGear = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5475352511539086860UL, 16358606561398759047UL), () => _ufle12jhs77_IdGear = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Rarity;
	public static BansheeGz.BGDatabase.BGFieldString _Rarity => _ufle12jhs77_Rarity ?? (_ufle12jhs77_Rarity = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5208517445898668775UL, 15620373196916554428UL), () => _ufle12jhs77_Rarity = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_PerkType;
	public static BansheeGz.BGDatabase.BGFieldString _PerkType => _ufle12jhs77_PerkType ?? (_ufle12jhs77_PerkType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5482939659572615491UL, 7288519745837319102UL), () => _ufle12jhs77_PerkType = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_PerkStat;
	public static BansheeGz.BGDatabase.BGFieldString _PerkStat => _ufle12jhs77_PerkStat ?? (_ufle12jhs77_PerkStat = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4797343983146385139UL, 1076810520718284684UL), () => _ufle12jhs77_PerkStat = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_Enemy.Factory _factory2_PFS = new DB_Enemy.Factory();
	private static readonly DB_DungeonWave.Factory _factory3_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonWaveEvent.Factory _factory4_PFS = new DB_DungeonWaveEvent.Factory();
	private static readonly DB_Weapon.Factory _factory5_PFS = new DB_Weapon.Factory();
	private static readonly DB_GearPerk.Factory _factory6_PFS = new DB_GearPerk.Factory();
	private static readonly DB_GameConfig.Factory _factory7_PFS = new DB_GameConfig.Factory();
	private DB_GearPerk() : base(MetaDefault)
	{
	}
	private DB_GearPerk(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_GearPerk(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_GearPerk(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_GearPerk FindEntity(Predicate<DB_GearPerk> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_GearPerk) entity)) as DB_GearPerk;
	}
	public static List<DB_GearPerk> FindEntities(Predicate<DB_GearPerk> filter, List<DB_GearPerk> result=null, Comparison<DB_GearPerk> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_GearPerk> action, Predicate<DB_GearPerk> filter=null, Comparison<DB_GearPerk> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_GearPerk) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_GearPerk) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_GearPerk)e1,(DB_GearPerk)e2));
	}
	public static DB_GearPerk GetEntity(BGId entityId) => (DB_GearPerk) MetaDefault.GetEntity(entityId);
	public static DB_GearPerk GetEntity(int index) => (DB_GearPerk) MetaDefault[index];
	public static DB_GearPerk GetEntity(string entityName) => (DB_GearPerk) MetaDefault.GetEntity(entityName);
}

public partial class DB_GameConfig : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_GameConfig(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_GameConfig(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5667507145059531655UL,13652673325387525797UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name => _name[Index];
	public System.String ConfigKey => _ConfigKey[Index];
	public System.String ConfigValue => _ConfigValue[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4939113393774973438UL, 13653894120683439280UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_ConfigKey;
	public static BansheeGz.BGDatabase.BGFieldString _ConfigKey => _ufle12jhs77_ConfigKey ?? (_ufle12jhs77_ConfigKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4927131490822964734UL, 11642070838833647758UL), () => _ufle12jhs77_ConfigKey = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_ConfigValue;
	public static BansheeGz.BGDatabase.BGFieldString _ConfigValue => _ufle12jhs77_ConfigValue ?? (_ufle12jhs77_ConfigValue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5231999877890111639UL, 10315952472082355112UL), () => _ufle12jhs77_ConfigValue = null));
	private static readonly DB_Equipment.Factory _factory0_PFS = new DB_Equipment.Factory();
	private static readonly DB_Dungeon.Factory _factory1_PFS = new DB_Dungeon.Factory();
	private static readonly DB_Enemy.Factory _factory2_PFS = new DB_Enemy.Factory();
	private static readonly DB_DungeonWave.Factory _factory3_PFS = new DB_DungeonWave.Factory();
	private static readonly DB_DungeonWaveEvent.Factory _factory4_PFS = new DB_DungeonWaveEvent.Factory();
	private static readonly DB_Weapon.Factory _factory5_PFS = new DB_Weapon.Factory();
	private static readonly DB_GearPerk.Factory _factory6_PFS = new DB_GearPerk.Factory();
	private static readonly DB_GameConfig.Factory _factory7_PFS = new DB_GameConfig.Factory();
	private DB_GameConfig() : base(MetaDefault)
	{
	}
	private DB_GameConfig(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_GameConfig(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_GameConfig(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_GameConfig FindEntity(Predicate<DB_GameConfig> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_GameConfig) entity)) as DB_GameConfig;
	}
	public static List<DB_GameConfig> FindEntities(Predicate<DB_GameConfig> filter, List<DB_GameConfig> result=null, Comparison<DB_GameConfig> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_GameConfig> action, Predicate<DB_GameConfig> filter=null, Comparison<DB_GameConfig> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_GameConfig) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_GameConfig) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_GameConfig)e1,(DB_GameConfig)e2));
	}
	public static DB_GameConfig GetEntity(BGId entityId) => (DB_GameConfig) MetaDefault.GetEntity(entityId);
	public static DB_GameConfig GetEntity(int index) => (DB_GameConfig) MetaDefault[index];
	public static DB_GameConfig GetEntity(string entityName) => (DB_GameConfig) MetaDefault.GetEntity(entityName);
}
#pragma warning restore 414
